<?php

return[
    "Time",
    "Hours",
    "Last Deposit",
    "Last Withdrawal",
    "OUR SERVICES",
    "Useful Links",
    "Subscribe to Newsletter",
    "Follow our social media",
    "Full name",
    "Email address",
    "Subject",
    "Your message",
    "Send Message",
    "No data to show",
    "Make Payment",
    "Receiver Email Address",
    "Enter Amount",
    "Select Wallet",
    "Interest Balance",
    "Main balance",
    "Enter Password",
    "Submit",
    "Click To Reset Password",
    "Reset Password",
    "Enter Your Email Address",
    "Send Password Reset Link",
    "Email Address",
    "Password",
    "Confirm Password",
    'submit',
    "Enter Your Code",
    "Enter 2fa code",
    "2FA Security Code",
    "Email Verification Code",
    "Didn't get Code? Click to",
    "Resend code",
    "Sms Verification Code",
    "Login To Your Account",
    "Email Or Username",
    "Enter Captcha",
    "Remember me",
    "Forgot password",
    "Create account",
    "Don't have an account?",
    "sign in",
    "Create An Account",
    "Sponsor By",
    "Sponsor",
    "First Name",
    "Last Name",
    "Phone Number",
    "Username",
    "I Agree with the Terms & conditions",
    "Login here",
    "Create Account",
    "Already have an account",
    "Blog Details",
    "Blogs",
    "Subscribe",
    "Useful Links",
    "Our Services",
    "get in touch",
    "All rights reserved",
    "Dashboard",
    "My Profile",
    "2FA Security",
    "Log Out",
    "level image",
    "Main Balance",
    "Interest Balance",
    "Deposit",
    "Invest",
    "Plan",
    "invest history",
    "Add Fund",
    "Fund History",
    "transfer",
    "transaction",
    "payout",
    "payout history",
    "my referral",
    "referral bonus",
    "Badges",
    "support ticket",
    "profile settings",
    "2FA Security",
    "Logout",
    "Read More",
    "Follow our social media",
    "Send Message",
    "Last Withdrawal",
    "Last Deposit",
    "deposit user image",
    "Amount",
    "Name",
    "Invest Now",
    "Enter amount",
    "Deposit Balance",
    "Interest Balance",
    "Checkout",
    "Lifetime Earning",
    "Capital",
    "Total",
    "Capital will back",
    "Profit For",
    "Every",
    "Lifetime",
    "Yes",
    "No",
    "Investor Image Missing",
    "Investor",
    "Invested",
    "Level",
    "badges",
    "All Badges",
    "Minimum Invest",
    "Minimum Deposit",
    "Minimum Earning",
    "No data to show",
    "Profile",
    "Add Fund",
    "Pay Now",
    "Payment",
    "Select Payment",
    "Select Currency",
    "Waiting for payment preview",
    "Select Crypto Currency",
    "Fund History",
    "Transaction ID",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Search",
    "Gateway",
    "Amount",
    "Charge",
    "Status",
    "Time",
    "All Payment",
    "Select a date",
    "Invest History",
    "SL",
    "Plan",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Completed",
    "For Lifetime",
    "COMPLETE",
    "Balance Transfer",
    "Receiver Email Address",
    "Select Wallet",
    "Main balance",
    "Interest Balance",
    "Enter Password",
    "Your Password",
    "Pay with",
    "Your Card Information",
    "Enter your card number",
    "Enter the name on your card",
    "CARD NAME",
    "CARD NUMBER",
    "EXPIRATION DATE",
    "CVC CODE",
    "Please Pay",
    "Pay Now",
    "To Get",
    "Pay Now",
    "PLEASE SEND EXACTLY",
    "SCAN TO SEND",
    "Please Pay",
    "Confirm Now",
    "Pay with PAYPAL",
    "Pay Now",
    "Pay with VoguePay",
    "Payout",
    "Select Transfer",
    "Select Bank Currency",
    "Automatic Payout",
    "Payout Method",
    "Request Amount",
    "Charge",
    "Charge Percentage",
    "Amount In Base Currency",
    "Select Bank Currency",
    "Paypal Id",
    "phone",
    "Email",
    "Select Recipient",
    "Select Recipient Type",
    "Payout Log",
    "Rejected Payment",
    "Detail",
    "Pending",
    "Complete",
    "Cancel",
    "Close",
    "Payout Money",
    "PAYOUT NOW",
    "Withdraw",
    "Investment Plan",
    "Name",
    "Price",
    "Profit",
    "Capital Back",
    "Action",
    "Profile Information",
    "Password Setting",
    "Search User",
    "SL No.",
    "Bonus From",
    "Amount",
    "Remarks",
    "Time",
    "My Referral",
    "My Referral link",
    "Copy Link",
    "Username",
    "Level",
    "Email",
    "Phone Number",
    "Joined At",
    "Create New Ticket",
    "Create Ticket",
    "Enter Subject",
    "Enter Message",
    "Support Ticket",
    "Create ticket",
    "Subject",
    "Status",
    "Last Reply",
    "Action",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Ticket",
    "Are you want to close ticket",
    "Confirmation",
    "Transaction",
    "Search for Transaction ID",
    "Remark",
    "Remarks",
    "2 Step Security",
    "Two Factor Authenticator",
    "Regenerate",
    "Copy Code",
    "Disable Two Factor Authenticator",
    "copy link",
    "Enable Two Factor Authenticator",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Enter Google Authenticator Code",
    "Verify",
    "Verify Your OTP to Disable",
    "Verify",
    "Enter Your Password",
    "Are you want to Re-generate Authenticator",
    "Do not miss any single important notification! Allow your browser to get instant push notification.",
    "Allow me",
    "Please allow your browser to get instant push notification. Allow it from notification setting.",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Total Invest",
    "Total Payout",
    "Total Referral Bonus",
    "Last Referral Bonus",
    "ROI Redeemed",
    "ROI Speed",
    "Invest Completed",
    "Day",
    "Month",
    "Year",
    "Invest now",
    "Login",
    "Investment",
    "Deposit Bonus",
    "Investment Bonus",
    "Your referral link",
    "Account Balance",
    "Interest",
    "Per",
    "hours",
    "Hours",
    "Amount In",
    "Payable Amount",
    "In Base Currency",
    "Make Payment",
    "Deposit Summary",
    "Payment Summary",
    "Select Payout Method",
    "Waiting for payout preview",
    "Confirm",
    "preferred language",
    "address",
    "KYC Information",
    "Your KYC is Verified",
    "Your KYC is Pending",
    "change password",
    "Current Password",
    "New Password",
    "Re-generate Confirmation",
    "Details",
    "I agree to all terms and policies",
    "Accept",
    "Phone",
    "Location",
    "Total Ticket",
    "The Last Referral Bonus",
    "Level",
    "Referral Link",
    "Account Statistics",
    "Latest Registered Partner",
    "Lang",
    "Transfer",
    "Payout History",
    "Referral Bonus",
    "Profile Settings",
    "Today Withdraw feature is off. Please try on one of these days:",
    "Contact Us",
    "Call",
    "Location",
    "Type Your Name",
    "Type Your E-mail",
    "Type Subject",
    "Type Your Message",
    "Something write here",
    "Message",
    "Full Name",
    "your email",
    "your message",
    "Our Location",
    "Delete your account",
    "When you delete your account, you lose access to Front account services, and we permanently delete your personal data.",
    "Confirm that I want to delete my account.",
    "Delete",
    "Confirmation",
    "Are you sure about deleting your account",
    "Confirm",
    "Close",
    "Clear all",
    "You have no notifications",
    "View Profile",
    "Quick Links",
    "Company Policy",
    "Your email",
    "Copyright",
    "All Rights Reserved",
    "Invest",
    "deposit user image",
    "Name",
    "Amount",
    "Gateway",
    "Date",
    "Withdraw User Image",
    "level",
    "Admin",
    "Socials",
    "Phone",
    "Email",
    "Address",
    "Your Massage",
    "Your Subject",
    "E-mail Address",
    "Your Name",
    "Send a massage",
    "by",
    "social share",
    "Search",
    "Search here",
    "Recent Post",
    "Remember me",
    "Forgot password",
    "Log In",
    "Username or Email",
    "Password",
    "Enter Captcha",
    "First Name",
    "Last Name",
    "User Name",
    "Confirm Password",
    "signup",
    "Already have an account",
    "Copied",
    "copy",
    "new notifications",
    "You have",
    "My Profile",
    "Account Balance",
    "Main Balance",
    "Interest Balance",
    "Hi",
    "What do you want to",
    "learn",
    "today",
    "Invest in yourself and take the first step towards achieving your dreams",
    "To do list",
    "Plan List",
    "Filter",
    "How would you like to pay",
    "Select Payment Method",
    "send money",
    "Confirm Payout",
    "Are you sure you want to terminate this investment",
    "status",
    "Filter",
    "Referral Bonus Filter",
    "Payout history filter",
    "Transaction Filter",
    "Fund History Filter",
    "Newsletter",
    "Login Here",
    "Recover Password",
    "Regain access with your seamless and secure account retrieval process in just a few clicks",
    "Team Investment",
    "Last Payout",
    "Home",
    "Last Payout",
    "Time has passed",
    "Terminated",
    "Referral Users",
    "Profile",
    "Select a Ticket to start messaging",
];
